### ISSUE TITLE
Reference to ocean properties in land specialization

### ISSUE THREAD

**Issue by martinjuckes** [ES-DOC/cmip6-specializations-landsurface#3]
The land_key_properties file (https://github.com/ES-DOC/cmip6-specializations-land/blob/master/land_key_properties.py ) contains a reference to "Physical properties of seawater in ocean" (line 56). Should be deleted or amended?

**Comment by davidhassell** [comment]
@martinjuckes : Thanks for spotting this - the file was seeded from an ocean description for the syntax, and so it is there in error. The repo is in an initiialisation phases and will take proper shape, with more .py files to come, over the next couple of days. David
