### ISSUE TITLE
Dynamic canopy height

### ISSUE THREAD

**Issue by martinjuckes** [ES-DOC/cmip6-specializations-landsurface#4]
It is expected that some CMIP6 models will have dynamic canopy height, others not (email from Chris Jones). It would be useful to capture this distinction in the model documentation. Perhaps with a `canopy_height` entry in `prognostic_vars_types`?

**Comment by davidhassell** [comment]
I will put this into the first draft - thanks

**Comment by davidhassell** [comment]
Fixed in d4b7e38
